// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/snake.proto

#include "proto/snake.pb.h"
#include "proto/snake.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace snake {

static const char* SnakeGame_method_names[] = {
  "/snake.SnakeGame/SendState",
};

std::unique_ptr< SnakeGame::Stub> SnakeGame::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SnakeGame::Stub> stub(new SnakeGame::Stub(channel, options));
  return stub;
}

SnakeGame::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendState_(SnakeGame_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SnakeGame::Stub::SendState(::grpc::ClientContext* context, const ::snake::GameAction& request, ::snake::GameState* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snake::GameAction, ::snake::GameState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendState_, context, request, response);
}

void SnakeGame::Stub::async::SendState(::grpc::ClientContext* context, const ::snake::GameAction* request, ::snake::GameState* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snake::GameAction, ::snake::GameState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendState_, context, request, response, std::move(f));
}

void SnakeGame::Stub::async::SendState(::grpc::ClientContext* context, const ::snake::GameAction* request, ::snake::GameState* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snake::GameState>* SnakeGame::Stub::PrepareAsyncSendStateRaw(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snake::GameState, ::snake::GameAction, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snake::GameState>* SnakeGame::Stub::AsyncSendStateRaw(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

SnakeGame::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SnakeGame_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SnakeGame::Service, ::snake::GameAction, ::snake::GameState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SnakeGame::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snake::GameAction* req,
             ::snake::GameState* resp) {
               return service->SendState(ctx, req, resp);
             }, this)));
}

SnakeGame::Service::~Service() {
}

::grpc::Status SnakeGame::Service::SendState(::grpc::ServerContext* context, const ::snake::GameAction* request, ::snake::GameState* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace snake

