# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/snake.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/snake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/snake.proto\x12\x05snake\"5\n\tGameState\x12\x0b\n\x03map\x18\x01 \x03(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"\x1c\n\nGameAction\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t2=\n\tSnakeGame\x12\x30\n\tSendState\x12\x11.snake.GameAction\x1a\x10.snake.GameStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.snake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMESTATE']._serialized_start=28
  _globals['_GAMESTATE']._serialized_end=81
  _globals['_GAMEACTION']._serialized_start=83
  _globals['_GAMEACTION']._serialized_end=111
  _globals['_SNAKEGAME']._serialized_start=113
  _globals['_SNAKEGAME']._serialized_end=174
# @@protoc_insertion_point(module_scope)
