// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/snake.proto
#ifndef GRPC_proto_2fsnake_2eproto__INCLUDED
#define GRPC_proto_2fsnake_2eproto__INCLUDED

#include "proto/snake.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace snake {

class SnakeGame final {
 public:
  static constexpr char const* service_full_name() {
    return "snake.SnakeGame";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendState(::grpc::ClientContext* context, const ::snake::GameAction& request, ::snake::GameState* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::snake::GameState>> AsyncSendState(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::snake::GameState>>(AsyncSendStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::snake::GameState>> PrepareAsyncSendState(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::snake::GameState>>(PrepareAsyncSendStateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendState(::grpc::ClientContext* context, const ::snake::GameAction* request, ::snake::GameState* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendState(::grpc::ClientContext* context, const ::snake::GameAction* request, ::snake::GameState* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::snake::GameState>* AsyncSendStateRaw(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::snake::GameState>* PrepareAsyncSendStateRaw(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendState(::grpc::ClientContext* context, const ::snake::GameAction& request, ::snake::GameState* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::snake::GameState>> AsyncSendState(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::snake::GameState>>(AsyncSendStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::snake::GameState>> PrepareAsyncSendState(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::snake::GameState>>(PrepareAsyncSendStateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendState(::grpc::ClientContext* context, const ::snake::GameAction* request, ::snake::GameState* response, std::function<void(::grpc::Status)>) override;
      void SendState(::grpc::ClientContext* context, const ::snake::GameAction* request, ::snake::GameState* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::snake::GameState>* AsyncSendStateRaw(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::snake::GameState>* PrepareAsyncSendStateRaw(::grpc::ClientContext* context, const ::snake::GameAction& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendState(::grpc::ServerContext* context, const ::snake::GameAction* request, ::snake::GameState* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendState() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendState(::grpc::ServerContext* /*context*/, const ::snake::GameAction* /*request*/, ::snake::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendState(::grpc::ServerContext* context, ::snake::GameAction* request, ::grpc::ServerAsyncResponseWriter< ::snake::GameState>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendState<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendState() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::snake::GameAction, ::snake::GameState>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::snake::GameAction* request, ::snake::GameState* response) { return this->SendState(context, request, response); }));}
    void SetMessageAllocatorFor_SendState(
        ::grpc::MessageAllocator< ::snake::GameAction, ::snake::GameState>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::snake::GameAction, ::snake::GameState>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendState(::grpc::ServerContext* /*context*/, const ::snake::GameAction* /*request*/, ::snake::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendState(
      ::grpc::CallbackServerContext* /*context*/, const ::snake::GameAction* /*request*/, ::snake::GameState* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendState<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendState() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendState(::grpc::ServerContext* /*context*/, const ::snake::GameAction* /*request*/, ::snake::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendState() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendState(::grpc::ServerContext* /*context*/, const ::snake::GameAction* /*request*/, ::snake::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendState() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendState(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendState(::grpc::ServerContext* /*context*/, const ::snake::GameAction* /*request*/, ::snake::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendState() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::snake::GameAction, ::snake::GameState>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::snake::GameAction, ::snake::GameState>* streamer) {
                       return this->StreamedSendState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendState(::grpc::ServerContext* /*context*/, const ::snake::GameAction* /*request*/, ::snake::GameState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::snake::GameAction,::snake::GameState>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendState<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendState<Service > StreamedService;
};

}  // namespace snake


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_proto_2fsnake_2eproto__INCLUDED
